# Generated by Django 3.2.4 on 2021-06-19 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idISBN', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de ISBN')),
                ('nombreLibro', models.CharField(max_length=50, verbose_name='Nombre del Libro')),
                ('autorLibro', models.CharField(max_length=50, verbose_name='Nombre del Autor')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion del libro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
