# Generated by Django 3.2.4 on 2021-06-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='idISBN',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False, verbose_name='Id de ISBN'),
        ),
    ]
