# Generated by Django 3.2.4 on 2021-06-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_libro_idisbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='idISBN',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='Id de ISBN'),
        ),
    ]
